### ISSUE TITLE
misleading project title. it is bluetooth, not wifi

### ISSUE THREAD

**Issue by lokeshsinhax** [InteractionOneSolutions/RN-WifiAttendance#2]
misleading project title. it is bluetooth, not wifi. :(
Mr. SkyTreasure, please correct it.

**Comment by SkyTreasure** [comment]
Please do the PR. Thank you

**Comment by lokeshsinhax** [comment]
Stop being so rude.

**Comment by lokeshsinhax** [comment]
Don't hurt my feelings like this. this is open source. open feelings.
